### ISSUE TITLE
dns-lexicon: run tests in EPEL 7

### ISSUE THREAD

**Issue by FelixSchwarz** [FelixSchwarz/certbot-epel7-python3#2]

**Comment by FelixSchwarz** [comment]
Unfortunately we can not run the test suite in EPEL 7 as there is no `python3-vcrpy` (and hence no `python3-pytest-vcr`). For Python 2 there is `python-vcrpy 1.5.2-1.el7` but no pytest plugin.

However I'd like to run at least some tests initially to ensure I'm not pushing something completely broken. Maybe I can add the `vcr` package to COPR (and disable tests when pushing the SPEC to Fedora's distgit).

**Comment by FelixSchwarz** [comment]
hmm, running the tests won't be as easy as I hoped: dns-lexicon requires `pytest >= 5.2` and `mock >= 3.0` but EPEL 7 ships `python36-pytest 2.9.2-4.el7` and `python36-mock 2.0.0-2.el7`. Maybe I can patch the test suite to make it work with older versions but this becomes a bit more work...

**Comment by FelixSchwarz** [comment]
Unfortunately it turned out we can not run the test suite on EPEL 7: [pytest-vcr](https://github.com/ktosiek/pytest-vcr/) requires [`pytest >= 3.0`](https://github.com/ktosiek/pytest-vcr/blob/0.1.0/setup.py#L26) even for the oldest released version.

**Comment by stethewwolf** [comment]
Hi,
is using virtualenv allowed? 
assuming I downoloaded lexicon code from [here](https://github.com/AnalogJ/lexicon) and my tag is  v3.3.28
I was able to run tests on centos7 with following commands:
```
$ yum install epel-release gcc cpp python-virtualenv
$  virtualenv env
$ source env/bin/activate
$ pip install pytest vcrpy tldextract
$ pytest
```
but actually the result is not excellent :  
```
==== 274 failed, 1350 passed, 177 skipped, 141 warnings, 161 error in 112.52 seconds ====
```

**Comment by FelixSchwarz** [comment]
>  is using virtualenv allowed?

For the actual Fedora build we don't have network connectivity. However for COPR we can use pip+internet and this might be helpful to ensure stuff would be working even when we can not verify this during the actual Fedora build.

Tests are likely failing because the VCR fixtures (cassettes) are not part of the tarball (they fixed this in later versions). Probably we need to switch the source to https://github.com/AnalogJ/lexicon/archive/refs/tags/v3.3.28.tar.gz so that the fixtures are available.
(Sorry, not much time right now. Downloading from github with proper file names + conditional for testing is not too hard but might be a bit frustrating if you have never done this. Feel free to try though. The idea for the conditional is to to use `%bcond_with tests`.)

**Comment by stethewwolf** [comment]
Hi, this [commit](https://github.com/stethewwolf/certbot-epel7-python3/commit/4431b0ab39451e01cd7ba58f2c53cd5e29028bba#diff-bb915f48df1b939040b8a99a27fbfea1ed228c02aa211b375b491e0962cae673)  is a small step forward, it should run checks ( not in epel7, where vcr is missing)

**Comment by FelixSchwarz** [comment]
Is the test suite passing for you with 4431b0ab39451e01cd7ba58f2c53cd5e29028bba? I tried to add your commit but I only get:

    =========================== short test summary info ============================
    ERROR lexicon/tests/providers/test_hetzner.py - dns.resolver.NoResolverConfig...
    !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
    ========================= 7 warnings, 1 error in 1.68s =========================

(this is with `fedpkg --release=f34 mockbuild`)

Also for Fedora I enabled the test suite a while ago ([spec file](https://src.fedoraproject.org/rpms/python-dns-lexicon/raw/rawhide/f/python-dns-lexicon.spec)) so what is missing is really the solution for EPEL 7 (if there is any).

If I remember correctly we need to use a github tarball so we have all the cassette files. You could try to get the tests passing in an EPEL 7 VM (without spec files, mock, just plain dev mode) by using the github export: `https://github.com/AnalogJ/lexicon/archive/v%{version}/lexicon-%{version}.tar.gz` (any 3.3.x version).

**Comment by FelixSchwarz** [comment]
`requests` package is likely the problem.

installing requests 2.16.0 (or later) fixes a least one (and likely all/most) crash in the test suite. Installing requests 2.15.1 (including `2.14.2` from EPEL 7) triggers the failure.

**Comment by FelixSchwarz** [comment]
done (maybe we can enable additional Python 3 tests once we have the boto/botocore Python 3 stack in EPEL)
